#!/usr/bin/env bash
set -eo pipefail
if [ "$1" = "init" ];then
  grep -A1000 '___CUT___' "$0"
  exit
elif [ "$1" = "set" ];then
  hour=$(date +%H | sed 's/^0//')
  minute=$(date +%M | sed 's/^0//')
  second=$(date +%S | sed 's/^0//')
  printf "_clock_face_hand_hour_ rotate 0 0 -%s\n" "$[$hour * 30 + ($minute / 2)]"
  printf "_clock_face_hand_minute_ rotate 0 0 -%s\n" "$[$minute * 6]"
  printf "_clock_face_hand_second_ rotate 0 0 -%s\n" "$[$second * 6]"
  #printf "_clock_face_hand_hour_ rotate 0 0 %s\n" "$[$hour * 30 + ($minute / 2)]"
  #printf "_clock_face_hand_minute_ rotate 0 0 %s\n" "$[$minute * 6]"
  #printf "_clock_face_hand_second_ rotate 0 0 %s\n" "$[$second * 6]"
else
  nonblocktail \
      <(echo $USER move 0 0 -30) \
      <("$0" init) \
      <(while true;do "$0" set;sleep 1;done) \
      /dev/stdin 2>/dev/null \
    | hackvr 2>/dev/null
fi
exit 0
___CUT___
_clock_face_digit_1_ addshape 2 4 3.99 7.66 0 5.99 7.66 0 5.99 9.66 0 3.99 9.66 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_2_ addshape 2 4 7.66 4.0 0 9.66 4.0 0 9.66 6.0 0 7.66 6.0 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_3_ addshape 2 4 9.0 -1.0 0 11.0 -1.0 0 11.0 1.0 0 9.0 1.0 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_4_ addshape 2 4 7.66 -6.0 0 9.66 -6.0 0 9.66 -4.0 0 7.66 -4.0 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_5_ addshape 2 4 4.0 -9.67 0 6.0 -9.67 0 6.0 -7.67 0 4.0 -7.67 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_6_ addshape 2 4 -1.0 -11.0 0 1.0 -11.0 0 1.0 -9.0 0 -1.0 -9.0 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_7_ addshape 2 4 -6.0 -9.67 0 -4.0 -9.67 0 -4.0 -7.67 0 -6.0 -7.67 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_8_ addshape 2 4 -9.67 -6.01 0 -7.67 -6.01 0 -7.67 -4.01 0 -9.67 -4.01 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_9_ addshape 2 4 -11.0 -1.01 0 -9.0 -1.01 0 -9.0 0.99 0 -11.0 0.99 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_10_ addshape 2 4 -9.67 3.99 0 -7.67 3.99 0 -7.67 5.99 0 -9.67 5.99 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_11_ addshape 2 4 -6.01 7.66 0 -4.01 7.66 0 -4.01 9.66 0 -6.01 9.66 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
_clock_face_digit_12_ addshape 2 4 -1.01 9.0 0 0.99 9.0 0 0.99 11.0 0 -1.01 11.0 0
_clock_face_hand_hour_ addshape 2 3 -1 -1 0   0 5 0  1 -1 0
_clock_face_hand_minute_ addshape 2 3 -.75 -.75 0   0 8 0  .75 -.75 0
_clock_face_hand_second_ addshape 2 3 -.25 -.25 0   0 10 0  .25 -.25 0
